# Site settings
title: Audrey Barthélemy-Musso
email: audrey.barthelemy.musso@gmail.com
description: "Docteur de l'Université"

author: "Audrey Barthélémy"
headTitle: "Mon CV de Docteur - Recherche - Psychologie Développement - Enfance"
metaDescription: "Audrey Barthélémy-Musso Mobile : 07.87.07.64.74 Email : audrey.barthelemy.musso@gmail.com Né le 25/06/83 à Toulouse Marié"

baseurl: ""
url: "http://docteur.audreybarthelemy.com"

# Build settings
markdown: kramdown
permalink: pretty

exclude:
- bower_components
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
- bower.json